project:
  type: website
  output-dir: docs
website:
  title: "IAB2025"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/guebin/IAB2025
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



